### ISSUE TITLE
Use wp user capabilities

### ISSUE THREAD

**Issue by SaculRennorb** [MrGunflame/DynamicTournament#20]
We should use wp capabilities to decide if a logged in user is allowed to edit the tournament scores. Probably also split up administration (edit team data) and moderation (edit scores only).

**Comment by MrGunflame** [comment]
Implemented in 6d9faca79c40701a1ffb8138029cbd8f5406ffd2 and ddc763635eee5a296773828234cda0f9dc55dcd4.
